# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink: /:title

# Setup
title:            Jacques de Vos
tagline:          Some thoughts and observations, mostly dev related
url:              http://jacdevos.github.io
paginate:         5
baseurl:          /
author:
  name:           Jacques de Vos
  url:            https://twitter.com/jacdevos
  email:          jacques@nreality.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jacdevos/jacdevos.github.io
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
